//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugin.CustomFanCurve.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Plugin.CustomFanCurve.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Offset Value (RPM).
        /// </summary>
        public static string AcousticOffsetAddRpm {
            get {
                return ResourceManager.GetString("AcousticOffsetAddRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exact RPM amount added to offset the secondary fan..
        /// </summary>
        public static string AcousticOffsetAddRpmDesc {
            get {
                return ResourceManager.GetString("AcousticOffsetAddRpmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Offset Delta (RPM).
        /// </summary>
        public static string AcousticOffsetDeltaRpm {
            get {
                return ResourceManager.GetString("AcousticOffsetDeltaRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum difference in RPM between fans before acoustic offsetting triggers..
        /// </summary>
        public static string AcousticOffsetDeltaRpmDesc {
            get {
                return ResourceManager.GetString("AcousticOffsetDeltaRpmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Tuning.
        /// </summary>
        public static string AcousticTuning {
            get {
                return ResourceManager.GetString("AcousticTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new control point at the end of the curve.
        /// </summary>
        public static string AddNodeTooltip {
            get {
                return ResourceManager.GetString("AddNodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to All Power Modes.
        /// </summary>
        public static string ApplyToAllModes {
            get {
                return ResourceManager.GetString("ApplyToAllModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom fan control in all power modes on Legion devices.
        /// </summary>
        public static string ApplyToAllModesDesc {
            get {
                return ResourceManager.GetString("ApplyToAllModesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM Calculation Interval (ms).
        /// </summary>
        public static string CalcInterval {
            get {
                return ResourceManager.GetString("CalcInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum delay between two RPM calculations, default 500ms.
        /// </summary>
        public static string CalcIntervalDesc {
            get {
                return ResourceManager.GetString("CalcIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Scheduling.
        /// </summary>
        public static string CalcScheduling {
            get {
                return ResourceManager.GetString("CalcScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache When Leaving Custom Mode.
        /// </summary>
        public static string ClearCacheOnLeave {
            get {
                return ResourceManager.GetString("ClearCacheOnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cached RPM/temperature state.
        /// </summary>
        public static string ClearCacheOnLeaveDesc {
            get {
                return ResourceManager.GetString("ClearCacheOnLeaveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Fan.
        /// </summary>
        public static string CpuFan {
            get {
                return ResourceManager.GetString("CpuFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Temperature (°C).
        /// </summary>
        public static string CriticalTemp {
            get {
                return ResourceManager.GetString("CriticalTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force maximum fan speed regardless of curve at this temperature..
        /// </summary>
        public static string CriticalTempDesc {
            get {
                return ResourceManager.GetString("CriticalTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Speed.
        /// </summary>
        public static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Mode.
        /// </summary>
        public static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output detailed debug logs when enabled.
        /// </summary>
        public static string DebugModeDesc {
            get {
                return ResourceManager.GetString("DebugModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this node.
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive Lookahead (Seconds).
        /// </summary>
        public static string DerivativeLookaheadSeconds {
            get {
                return ResourceManager.GetString("DerivativeLookaheadSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How far into the future to predict temperatures when a spike is detected..
        /// </summary>
        public static string DerivativeLookaheadSecondsDesc {
            get {
                return ResourceManager.GetString("DerivativeLookaheadSecondsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Spike Threshold (°C/s).
        /// </summary>
        public static string DerivativeSpikeThreshold {
            get {
                return ResourceManager.GetString("DerivativeSpikeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudden temperature spike rate required to activate predictive cooling..
        /// </summary>
        public static string DerivativeSpikeThresholdDesc {
            get {
                return ResourceManager.GetString("DerivativeSpikeThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Smoothing (EMA Alpha).
        /// </summary>
        public static string EmaAlpha {
            get {
                return ResourceManager.GetString("EmaAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight of new temperature readings. Lower = smoother but slower..
        /// </summary>
        public static string EmaAlphaDesc {
            get {
                return ResourceManager.GetString("EmaAlphaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Acoustic Offsetting.
        /// </summary>
        public static string EnableAcousticOffset {
            get {
                return ResourceManager.GetString("EnableAcousticOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents annoying beat frequencies by shifting fan speeds when they are too similar..
        /// </summary>
        public static string EnableAcousticOffsetDesc {
            get {
                return ResourceManager.GetString("EnableAcousticOffsetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Fan Curve.
        /// </summary>
        public static string EnableCurve {
            get {
                return ResourceManager.GetString("EnableCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore BIOS auto fan control when disabled.
        /// </summary>
        public static string EnableCurveDesc {
            get {
                return ResourceManager.GetString("EnableCurveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Fan Curve.
        /// </summary>
        public static string EnableCustomFanCurve {
            get {
                return ResourceManager.GetString("EnableCustomFanCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Smart Auto (Experimental).
        /// </summary>
        public static string EnableSmartAuto {
            get {
                return ResourceManager.GetString("EnableSmartAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Spin-Up Boost.
        /// </summary>
        public static string EnableSpinUp {
            get {
                return ResourceManager.GetString("EnableSpinUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefly pulses the fans at high speed to overcome static friction before settling to low targets..
        /// </summary>
        public static string EnableSpinUpDesc {
            get {
                return ResourceManager.GetString("EnableSpinUpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Speed.
        /// </summary>
        public static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Refresh on Enable.
        /// </summary>
        public static string ForceRefreshOnEnable {
            get {
                return ResourceManager.GetString("ForceRefreshOnEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately synchronizes the hardware cooling state when the custom curve is activated..
        /// </summary>
        public static string ForceRefreshOnEnableDesc {
            get {
                return ResourceManager.GetString("ForceRefreshOnEnableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Refresh on Mode Switch.
        /// </summary>
        public static string ForceRefreshOnSwitch {
            get {
                return ResourceManager.GetString("ForceRefreshOnSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-apply fan control after switching power modes.
        /// </summary>
        public static string ForceRefreshOnSwitchDesc {
            get {
                return ResourceManager.GetString("ForceRefreshOnSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Speed....
        /// </summary>
        public static string FullSpeedActive {
            get {
                return ResourceManager.GetString("FullSpeedActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open global settings.
        /// </summary>
        public static string GlobalSettingsTooltip {
            get {
                return ResourceManager.GetString("GlobalSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Fan.
        /// </summary>
        public static string GpuFan {
            get {
                return ResourceManager.GetString("GpuFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hysteresis.
        /// </summary>
        public static string Hysteresis {
            get {
                return ResourceManager.GetString("Hysteresis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hysteresis Deadzone Temp (°C).
        /// </summary>
        public static string HysteresisDeadzoneTemp {
            get {
                return ResourceManager.GetString("HysteresisDeadzoneTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature padding to prevent fans from aggressively ramping up and down when hovering on a curve node..
        /// </summary>
        public static string HysteresisDeadzoneTempDesc {
            get {
                return ResourceManager.GetString("HysteresisDeadzoneTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Zero Temperature.
        /// </summary>
        public static string IgnoreZeroTemp {
            get {
                return ResourceManager.GetString("IgnoreZeroTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip processing when sensor returns 0.
        /// </summary>
        public static string IgnoreZeroTempDesc {
            get {
                return ResourceManager.GetString("IgnoreZeroTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Monitor.
        /// </summary>
        public static string LiveMonitor {
            get {
                return ResourceManager.GetString("LiveMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Safety &amp; Smoothing.
        /// </summary>
        public static string MathematicalConstants {
            get {
                return ResourceManager.GetString("MathematicalConstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Speed.
        /// </summary>
        public static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all fans at maximum speed.
        /// </summary>
        public static string MaxSpeedTooltip {
            get {
                return ResourceManager.GetString("MaxSpeedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Switch.
        /// </summary>
        public static string ModeSwitch {
            get {
                return ResourceManager.GetString("ModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power/Thermal Mode Switch Behavior.
        /// </summary>
        public static string ModeSwitchTitle {
            get {
                return ResourceManager.GetString("ModeSwitchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Delta Threshold (W).
        /// </summary>
        public static string PowerDeltaThreshold {
            get {
                return ResourceManager.GetString("PowerDeltaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum change in wattage before forcing a recalculation.
        /// </summary>
        public static string PowerDeltaThresholdDesc {
            get {
                return ResourceManager.GetString("PowerDeltaThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive Engine.
        /// </summary>
        public static string PredictiveEngine {
            get {
                return ResourceManager.GetString("PredictiveEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to restore custom curve.
        /// </summary>
        public static string RecoverCurve {
            get {
                return ResourceManager.GetString("RecoverCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Count.
        /// </summary>
        public static string RefreshCount {
            get {
                return ResourceManager.GetString("RefreshCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of refresh cycles after mode switch, default 2.
        /// </summary>
        public static string RefreshCountDesc {
            get {
                return ResourceManager.GetString("RefreshCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Interval (ms).
        /// </summary>
        public static string RefreshInterval {
            get {
                return ResourceManager.GetString("RefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between multiple refreshes, default 250ms.
        /// </summary>
        public static string RefreshIntervalDesc {
            get {
                return ResourceManager.GetString("RefreshIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Minimum Fan Percentage (%).
        /// </summary>
        public static string SafeMaxPercentAtMaxTemp {
            get {
                return ResourceManager.GetString("SafeMaxPercentAtMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guaranteed minimum fan percentage when the hardware reaches the critical maximum temperature..
        /// </summary>
        public static string SafeMaxPercentAtMaxTempDesc {
            get {
                return ResourceManager.GetString("SafeMaxPercentAtMaxTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Maximum Temperature (°C).
        /// </summary>
        public static string SafeMaxTemp {
            get {
                return ResourceManager.GetString("SafeMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The critical maximum hardware temperature before the safety net forcefully overrides the fan curve..
        /// </summary>
        public static string SafeMaxTempDesc {
            get {
                return ResourceManager.GetString("SafeMaxTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Minimum Temperature (°C).
        /// </summary>
        public static string SafeMinTemp {
            get {
                return ResourceManager.GetString("SafeMinTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum bound for safe hardware temperature evaluation..
        /// </summary>
        public static string SafeMinTempDesc {
            get {
                return ResourceManager.GetString("SafeMinTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes take effect immediately after clicking Save..
        /// </summary>
        public static string SaveHint {
            get {
                return ResourceManager.GetString("SaveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor &amp; Calc.
        /// </summary>
        public static string SensorAndCalc {
            get {
                return ResourceManager.GetString("SensorAndCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Polling Interval (ms).
        /// </summary>
        public static string SensorInterval {
            get {
                return ResourceManager.GetString("SensorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval for reading temperature data, default 500ms.
        /// </summary>
        public static string SensorIntervalDesc {
            get {
                return ResourceManager.GetString("SensorIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Polling.
        /// </summary>
        public static string SensorPolling {
            get {
                return ResourceManager.GetString("SensorPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Source.
        /// </summary>
        public static string SensorSource {
            get {
                return ResourceManager.GetString("SensorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average of CPU / GPU.
        /// </summary>
        public static string SensorSourceAverageCpuGpu {
            get {
                return ResourceManager.GetString("SensorSourceAverageCpuGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default (Auto).
        /// </summary>
        public static string SensorSourceDefault {
            get {
                return ResourceManager.GetString("SensorSourceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects which hardware temperature this fan curve actively monitors and responds to..
        /// </summary>
        public static string SensorSourceDesc {
            get {
                return ResourceManager.GetString("SensorSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of CPU / GPU.
        /// </summary>
        public static string SensorSourceMaxCpuGpu {
            get {
                return ResourceManager.GetString("SensorSourceMaxCpuGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings — Custom Fan Curve (WMI).
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual fan curves are disabled. The Fuzzy Logic engine is managing thermals based on power consumption..
        /// </summary>
        public static string SmartAutoDashboardSubtitle {
            get {
                return ResourceManager.GetString("SmartAutoDashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomous Thermal Control.
        /// </summary>
        public static string SmartAutoDashboardTitle {
            get {
                return ResourceManager.GetString("SmartAutoDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision:.
        /// </summary>
        public static string SmartAutoDecision {
            get {
                return ResourceManager.GetString("SmartAutoDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomously controls fan speeds using Fuzzy Logic based on hardware temperature and power draw. Disables manual fan curves..
        /// </summary>
        public static string SmartAutoDescription {
            get {
                return ResourceManager.GetString("SmartAutoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Load:.
        /// </summary>
        public static string SmartAutoPowerLoad {
            get {
                return ResourceManager.GetString("SmartAutoPowerLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Speed:.
        /// </summary>
        public static string SmartAutoTargetOutput {
            get {
                return ResourceManager.GetString("SmartAutoTargetOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal State:.
        /// </summary>
        public static string SmartAutoThermalState {
            get {
                return ResourceManager.GetString("SmartAutoThermalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin-Up Boost.
        /// </summary>
        public static string SpinUpBoost {
            get {
                return ResourceManager.GetString("SpinUpBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a fan is stopped, it needs a higher initial RPM to overcome static friction.
        ///With spin-up boost enabled, the system briefly runs the fan at a higher RPM before settling to the target..
        /// </summary>
        public static string SpinUpDesc {
            get {
                return ResourceManager.GetString("SpinUpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin-Up Duration (ms).
        /// </summary>
        public static string SpinUpDuration {
            get {
                return ResourceManager.GetString("SpinUpDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long the spin-up RPM lasts, default 300ms.
        /// </summary>
        public static string SpinUpDurationDesc {
            get {
                return ResourceManager.GetString("SpinUpDurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin-Up RPM.
        /// </summary>
        public static string SpinUpRpm {
            get {
                return ResourceManager.GetString("SpinUpRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary RPM during spin-up, default 3000.
        /// </summary>
        public static string SpinUpRpmDesc {
            get {
                return ResourceManager.GetString("SpinUpRpmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Down Glide Rate (RPM/sec).
        /// </summary>
        public static string StepDownRate {
            get {
                return ResourceManager.GetString("StepDownRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum RPM drop per second while cooling down..
        /// </summary>
        public static string StepDownRateDesc {
            get {
                return ResourceManager.GetString("StepDownRateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Down Protection Delta (RPM).
        /// </summary>
        public static string StepDownSpamDelta {
            get {
                return ResourceManager.GetString("StepDownSpamDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum RPM drop required before sending a hardware command..
        /// </summary>
        public static string StepDownSpamDeltaDesc {
            get {
                return ResourceManager.GetString("StepDownSpamDeltaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Fan.
        /// </summary>
        public static string SystemFan {
            get {
                return ResourceManager.GetString("SystemFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target fan speed percentage (0-100).
        /// </summary>
        public static string TargetPercent {
            get {
                return ResourceManager.GetString("TargetPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Speed.
        /// </summary>
        public static string TargetSpeed {
            get {
                return ResourceManager.GetString("TargetSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Change Threshold (°C).
        /// </summary>
        public static string TempDeltaThreshold {
            get {
                return ResourceManager.GetString("TempDeltaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum temperature change to trigger recalculation, default 0.5°C.
        /// </summary>
        public static string TempDeltaThresholdDesc {
            get {
                return ResourceManager.GetString("TempDeltaThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature value (°C).
        /// </summary>
        public static string TemperatureUnit {
            get {
                return ResourceManager.GetString("TemperatureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI &amp; Monitoring.
        /// </summary>
        public static string UiAndMonitoring {
            get {
                return ResourceManager.GetString("UiAndMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Save Debounce Delay (ms).
        /// </summary>
        public static string UiDebounceDelay {
            get {
                return ResourceManager.GetString("UiDebounceDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay before writing to disk after dragging a curve node..
        /// </summary>
        public static string UiDebounceDelayDesc {
            get {
                return ResourceManager.GetString("UiDebounceDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Update Interval (ms).
        /// </summary>
        public static string UiUpdateInterval {
            get {
                return ResourceManager.GetString("UiUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor panel refresh interval, default 1000ms.
        /// </summary>
        public static string UiUpdateIntervalDesc {
            get {
                return ResourceManager.GetString("UiUpdateIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Cached Snapshot for Forced Refresh.
        /// </summary>
        public static string UseCachedSnapshot {
            get {
                return ResourceManager.GetString("UseCachedSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of waiting for new sensor readings.
        /// </summary>
        public static string UseCachedSnapshotDesc {
            get {
                return ResourceManager.GetString("UseCachedSnapshotDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Fan Curve (WMI).
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Max Each Cycle in Full Speed.
        /// </summary>
        public static string WriteEachCycle {
            get {
                return ResourceManager.GetString("WriteEachCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write max RPM every calculation cycle in full speed mode.
        /// </summary>
        public static string WriteEachCycleDesc {
            get {
                return ResourceManager.GetString("WriteEachCycleDesc", resourceCulture);
            }
        }
    }
}
