//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugin.CustomFanCurve.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Plugin.CustomFanCurve.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Offset Value.
        /// </summary>
        public static string AcousticOffsetAddRpm {
            get {
                return ResourceManager.GetString("AcousticOffsetAddRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target RPM offset added to the secondary fan to mitigate harmonic resonance..
        /// </summary>
        public static string AcousticOffsetAddRpmDesc {
            get {
                return ResourceManager.GetString("AcousticOffsetAddRpmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Offset Delta.
        /// </summary>
        public static string AcousticOffsetDeltaRpm {
            get {
                return ResourceManager.GetString("AcousticOffsetDeltaRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum target RPM difference between fans below which acoustic offsetting will trigger..
        /// </summary>
        public static string AcousticOffsetDeltaRpmDesc {
            get {
                return ResourceManager.GetString("AcousticOffsetDeltaRpmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Offset.
        /// </summary>
        public static string AcousticTuning {
            get {
                return ResourceManager.GetString("AcousticTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new node.
        /// </summary>
        public static string AddNodeTooltip {
            get {
                return ResourceManager.GetString("AddNodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Write RPM.
        /// </summary>
        public static string AlwaysWriteRpm {
            get {
                return ResourceManager.GetString("AlwaysWriteRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces writing the target RPM to the EC on every calculation cycle, regardless of speed changes..
        /// </summary>
        public static string AlwaysWriteRpmDesc {
            get {
                return ResourceManager.GetString("AlwaysWriteRpmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to All Power Modes.
        /// </summary>
        public static string ApplyToAllModes {
            get {
                return ResourceManager.GetString("ApplyToAllModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable custom fan control in all power modes..
        /// </summary>
        public static string ApplyToAllModesDesc {
            get {
                return ResourceManager.GetString("ApplyToAllModesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM Calculation Interval.
        /// </summary>
        public static string CalcInterval {
            get {
                return ResourceManager.GetString("CalcInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum delay (ms) between speed recalculations..
        /// </summary>
        public static string CalcIntervalDesc {
            get {
                return ResourceManager.GetString("CalcIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Scheduling.
        /// </summary>
        public static string CalcScheduling {
            get {
                return ResourceManager.GetString("CalcScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache When Leaving Custom Mode.
        /// </summary>
        public static string ClearCacheOnLeave {
            get {
                return ResourceManager.GetString("ClearCacheOnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears cached RPM and temperature state when custom fan control is disabled..
        /// </summary>
        public static string ClearCacheOnLeaveDesc {
            get {
                return ResourceManager.GetString("ClearCacheOnLeaveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Fan.
        /// </summary>
        public static string CpuFan {
            get {
                return ResourceManager.GetString("CpuFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Temperature.
        /// </summary>
        public static string CriticalTemp {
            get {
                return ResourceManager.GetString("CriticalTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces maximum fan speed regardless of the current fan curve once this temperature threshold (°C) is reached..
        /// </summary>
        public static string CriticalTempDesc {
            get {
                return ResourceManager.GetString("CriticalTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety &amp; Overrides.
        /// </summary>
        public static string CriticalTempSafety {
            get {
                return ResourceManager.GetString("CriticalTempSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Speed.
        /// </summary>
        public static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Mode.
        /// </summary>
        public static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs detailed diagnostics and behavior logs when enabled..
        /// </summary>
        public static string DebugModeDesc {
            get {
                return ResourceManager.GetString("DebugModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this node.
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive Lookahead.
        /// </summary>
        public static string DerivativeLookaheadSeconds {
            get {
                return ResourceManager.GetString("DerivativeLookaheadSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time interval (s) to project future temperatures when a spike is detected..
        /// </summary>
        public static string DerivativeLookaheadSecondsDesc {
            get {
                return ResourceManager.GetString("DerivativeLookaheadSecondsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Spike Threshold.
        /// </summary>
        public static string DerivativeSpikeThreshold {
            get {
                return ResourceManager.GetString("DerivativeSpikeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature rate-of-change threshold (°C/s) required to trigger predictive cooling..
        /// </summary>
        public static string DerivativeSpikeThresholdDesc {
            get {
                return ResourceManager.GetString("DerivativeSpikeThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMA Smoothing Coefficient.
        /// </summary>
        public static string EmaAlpha {
            get {
                return ResourceManager.GetString("EmaAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight of new temperature readings in the Exponential Moving Average filter. Lower values increase smoothing but introduce response latency..
        /// </summary>
        public static string EmaAlphaDesc {
            get {
                return ResourceManager.GetString("EmaAlphaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooths temperature reading fluctuations using an Exponential Moving Average (EMA) filter..
        /// </summary>
        public static string EmaDesc {
            get {
                return ResourceManager.GetString("EmaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic Offsetting.
        /// </summary>
        public static string EnableAcousticOffset {
            get {
                return ResourceManager.GetString("EnableAcousticOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigates audible beat frequencies and harmonic resonance by applying a speed offset when fan targets are too similar..
        /// </summary>
        public static string EnableAcousticOffsetDesc {
            get {
                return ResourceManager.GetString("EnableAcousticOffsetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Fan Curve.
        /// </summary>
        public static string EnableCurve {
            get {
                return ResourceManager.GetString("EnableCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores default BIOS automatic fan control when disabled..
        /// </summary>
        public static string EnableCurveDesc {
            get {
                return ResourceManager.GetString("EnableCurveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Fan Curve.
        /// </summary>
        public static string EnableCustomFanCurve {
            get {
                return ResourceManager.GetString("EnableCustomFanCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Smoothing.
        /// </summary>
        public static string EnableEma {
            get {
                return ResourceManager.GetString("EnableEma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hysteresis.
        /// </summary>
        public static string EnableHysteresis {
            get {
                return ResourceManager.GetString("EnableHysteresis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Write Suppression.
        /// </summary>
        public static string EnableMinimumRpmChangeToApply {
            get {
                return ResourceManager.GetString("EnableMinimumRpmChangeToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppresses WMI updates if the change in target RPM is below the specified threshold..
        /// </summary>
        public static string EnableMinimumRpmChangeToApplyDesc {
            get {
                return ResourceManager.GetString("EnableMinimumRpmChangeToApplyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Power Delta Filter.
        /// </summary>
        public static string EnablePowerDeltaThreshold {
            get {
                return ResourceManager.GetString("EnablePowerDeltaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters out recalculations if the power draw change is smaller than the threshold..
        /// </summary>
        public static string EnablePowerDeltaThresholdDesc {
            get {
                return ResourceManager.GetString("EnablePowerDeltaThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive Engine.
        /// </summary>
        public static string EnablePredictiveEngine {
            get {
                return ResourceManager.GetString("EnablePredictiveEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Auto (Experimental).
        /// </summary>
        public static string EnableSmartAuto {
            get {
                return ResourceManager.GetString("EnableSmartAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin-Up Boost.
        /// </summary>
        public static string EnableSpinUp {
            get {
                return ResourceManager.GetString("EnableSpinUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Briefly accelerates the fans to a higher speed to overcome static friction before settling to low targets..
        /// </summary>
        public static string EnableSpinUpDesc {
            get {
                return ResourceManager.GetString("EnableSpinUpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Down Gliding.
        /// </summary>
        public static string EnableStepDownGlide {
            get {
                return ResourceManager.GetString("EnableStepDownGlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Temperature Delta Filter.
        /// </summary>
        public static string EnableTemperatureDeltaThreshold {
            get {
                return ResourceManager.GetString("EnableTemperatureDeltaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters out recalculations if the temperature change is smaller than the threshold..
        /// </summary>
        public static string EnableTemperatureDeltaThresholdDesc {
            get {
                return ResourceManager.GetString("EnableTemperatureDeltaThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Safety Net.
        /// </summary>
        public static string EnableThermalSafetyNet {
            get {
                return ResourceManager.GetString("EnableThermalSafetyNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Speed.
        /// </summary>
        public static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Refresh on Enable.
        /// </summary>
        public static string ForceRefreshOnEnable {
            get {
                return ResourceManager.GetString("ForceRefreshOnEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately synchronizes the hardware cooling state when the custom curve is activated..
        /// </summary>
        public static string ForceRefreshOnEnableDesc {
            get {
                return ResourceManager.GetString("ForceRefreshOnEnableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Refresh on Mode Switch.
        /// </summary>
        public static string ForceRefreshOnSwitch {
            get {
                return ResourceManager.GetString("ForceRefreshOnSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-applies custom fan curve targets after switching power modes..
        /// </summary>
        public static string ForceRefreshOnSwitchDesc {
            get {
                return ResourceManager.GetString("ForceRefreshOnSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Write When Target is 0.
        /// </summary>
        public static string ForceWriteWhenRpmZero {
            get {
                return ResourceManager.GetString("ForceWriteWhenRpmZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces writing to the EC when target RPM is 0 to ensure fans halt completely..
        /// </summary>
        public static string ForceWriteWhenRpmZeroDesc {
            get {
                return ResourceManager.GetString("ForceWriteWhenRpmZeroDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Speed....
        /// </summary>
        public static string FullSpeedActive {
            get {
                return ResourceManager.GetString("FullSpeedActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuzzy Logic.
        /// </summary>
        public static string FuzzyLogicEngine {
            get {
                return ResourceManager.GetString("FuzzyLogicEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Fan.
        /// </summary>
        public static string GpuFan {
            get {
                return ResourceManager.GetString("GpuFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hysteresis.
        /// </summary>
        public static string Hysteresis {
            get {
                return ResourceManager.GetString("Hysteresis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hysteresis Deadzone Temp.
        /// </summary>
        public static string HysteresisDeadzoneTemp {
            get {
                return ResourceManager.GetString("HysteresisDeadzoneTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature threshold buffer (°C) to prevent fan speed oscillation when temperature fluctuates around a curve node..
        /// </summary>
        public static string HysteresisDeadzoneTempDesc {
            get {
                return ResourceManager.GetString("HysteresisDeadzoneTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooths fan behavior by maintaining target speeds when temperature changes are minor..
        /// </summary>
        public static string HysteresisDesc {
            get {
                return ResourceManager.GetString("HysteresisDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Zero Temperature.
        /// </summary>
        public static string IgnoreZeroTemp {
            get {
                return ResourceManager.GetString("IgnoreZeroTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skips speed calculations when temperature sensors temporarily return zero..
        /// </summary>
        public static string IgnoreZeroTempDesc {
            get {
                return ResourceManager.GetString("IgnoreZeroTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Monitor.
        /// </summary>
        public static string LiveMonitor {
            get {
                return ResourceManager.GetString("LiveMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Speed.
        /// </summary>
        public static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs all fans at maximum speed..
        /// </summary>
        public static string MaxSpeedTooltip {
            get {
                return ResourceManager.GetString("MaxSpeedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum RPM Change to Apply.
        /// </summary>
        public static string MinimumRpmChangeToApply {
            get {
                return ResourceManager.GetString("MinimumRpmChangeToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress writes to WMI if the target RPM change is smaller than this value to reduce WMI call overhead..
        /// </summary>
        public static string MinimumRpmChangeToApplyDesc {
            get {
                return ResourceManager.GetString("MinimumRpmChangeToApplyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Switch.
        /// </summary>
        public static string ModeSwitch {
            get {
                return ResourceManager.GetString("ModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Switch Behavior.
        /// </summary>
        public static string ModeSwitchTitle {
            get {
                return ResourceManager.GetString("ModeSwitchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Delta Threshold.
        /// </summary>
        public static string PowerDeltaThreshold {
            get {
                return ResourceManager.GetString("PowerDeltaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum change in power consumption (W) required to trigger a recalculation..
        /// </summary>
        public static string PowerDeltaThresholdDesc {
            get {
                return ResourceManager.GetString("PowerDeltaThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive Engine.
        /// </summary>
        public static string PredictiveEngine {
            get {
                return ResourceManager.GetString("PredictiveEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anticipates temperature spikes based on rate-of-change and proactively accelerates fans..
        /// </summary>
        public static string PredictiveEngineDesc {
            get {
                return ResourceManager.GetString("PredictiveEngineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing hardware....
        /// </summary>
        public static string ProbingHardware {
            get {
                return ResourceManager.GetString("ProbingHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Custom Curve.
        /// </summary>
        public static string RecoverCurve {
            get {
                return ResourceManager.GetString("RecoverCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Count.
        /// </summary>
        public static string RefreshCount {
            get {
                return ResourceManager.GetString("RefreshCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of refresh cycles executed after a power mode switch..
        /// </summary>
        public static string RefreshCountDesc {
            get {
                return ResourceManager.GetString("RefreshCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Interval.
        /// </summary>
        public static string RefreshInterval {
            get {
                return ResourceManager.GetString("RefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay (ms) between multiple refresh cycles..
        /// </summary>
        public static string RefreshIntervalDesc {
            get {
                return ResourceManager.GetString("RefreshIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverts all custom fan curve settings to their original factory values..
        /// </summary>
        public static string ResetToDefaultsDesc {
            get {
                return ResourceManager.GetString("ResetToDefaultsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Minimum Fan Percentage.
        /// </summary>
        public static string SafeMaxPercentAtMaxTemp {
            get {
                return ResourceManager.GetString("SafeMaxPercentAtMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed minimum fan speed percentage when the safe maximum temperature is reached..
        /// </summary>
        public static string SafeMaxPercentAtMaxTempDesc {
            get {
                return ResourceManager.GetString("SafeMaxPercentAtMaxTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Maximum Temperature.
        /// </summary>
        public static string SafeMaxTemp {
            get {
                return ResourceManager.GetString("SafeMaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temperature threshold (°C) at which the safety net enforces the maximum safety fan speed floor..
        /// </summary>
        public static string SafeMaxTempDesc {
            get {
                return ResourceManager.GetString("SafeMaxTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Minimum Temperature.
        /// </summary>
        public static string SafeMinTemp {
            get {
                return ResourceManager.GetString("SafeMinTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temperature threshold (°C) above which the safety net speed floor begins scaling upward..
        /// </summary>
        public static string SafeMinTempDesc {
            get {
                return ResourceManager.GetString("SafeMinTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes take effect immediately after clicking Save..
        /// </summary>
        public static string SaveHint {
            get {
                return ResourceManager.GetString("SaveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor &amp; Calculation.
        /// </summary>
        public static string SensorAndCalc {
            get {
                return ResourceManager.GetString("SensorAndCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Polling Interval.
        /// </summary>
        public static string SensorInterval {
            get {
                return ResourceManager.GetString("SensorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (ms) for polling temperature sensor data..
        /// </summary>
        public static string SensorIntervalDesc {
            get {
                return ResourceManager.GetString("SensorIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Polling.
        /// </summary>
        public static string SensorPolling {
            get {
                return ResourceManager.GetString("SensorPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Source.
        /// </summary>
        public static string SensorSource {
            get {
                return ResourceManager.GetString("SensorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average of CPU / GPU.
        /// </summary>
        public static string SensorSourceAverageCpuGpu {
            get {
                return ResourceManager.GetString("SensorSourceAverageCpuGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default (Auto).
        /// </summary>
        public static string SensorSourceDefault {
            get {
                return ResourceManager.GetString("SensorSourceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the temperature sensor monitored by this fan curve..
        /// </summary>
        public static string SensorSourceDesc {
            get {
                return ResourceManager.GetString("SensorSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of CPU / GPU.
        /// </summary>
        public static string SensorSourceMaxCpuGpu {
            get {
                return ResourceManager.GetString("SensorSourceMaxCpuGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens settings panel..
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual fan curves are disabled. The autonomous thermal controller is managing fan speeds based on real-time temperature and power consumption..
        /// </summary>
        public static string SmartAutoDashboardSubtitle {
            get {
                return ResourceManager.GetString("SmartAutoDashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomous Thermal Control.
        /// </summary>
        public static string SmartAutoDashboardTitle {
            get {
                return ResourceManager.GetString("SmartAutoDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision:.
        /// </summary>
        public static string SmartAutoDecision {
            get {
                return ResourceManager.GetString("SmartAutoDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomously manages fan speeds using fuzzy logic based on real-time temperature and power consumption. Manual fan curves are bypassed..
        /// </summary>
        public static string SmartAutoDescription {
            get {
                return ResourceManager.GetString("SmartAutoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware not supported..
        /// </summary>
        public static string SmartAutoHardwareNotSupported {
            get {
                return ResourceManager.GetString("SmartAutoHardwareNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive (requires Custom Mode or &quot;Apply to All Power Modes&quot; to be enabled)..
        /// </summary>
        public static string SmartAutoInactiveRequiresCustom {
            get {
                return ResourceManager.GetString("SmartAutoInactiveRequiresCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Load:.
        /// </summary>
        public static string SmartAutoPowerLoad {
            get {
                return ResourceManager.GetString("SmartAutoPowerLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Speed:.
        /// </summary>
        public static string SmartAutoTargetOutput {
            get {
                return ResourceManager.GetString("SmartAutoTargetOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal State:.
        /// </summary>
        public static string SmartAutoThermalState {
            get {
                return ResourceManager.GetString("SmartAutoThermalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin-Up Boost.
        /// </summary>
        public static string SpinUpBoost {
            get {
                return ResourceManager.GetString("SpinUpBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a fan is stopped, it needs a higher initial RPM to overcome static friction.
        ///With spin-up boost enabled, the system briefly runs the fan at a higher RPM before settling to the target..
        /// </summary>
        public static string SpinUpDesc {
            get {
                return ResourceManager.GetString("SpinUpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin-Up Duration.
        /// </summary>
        public static string SpinUpDuration {
            get {
                return ResourceManager.GetString("SpinUpDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (ms) of the spin-up boost phase..
        /// </summary>
        public static string SpinUpDurationDesc {
            get {
                return ResourceManager.GetString("SpinUpDurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin-Up RPM.
        /// </summary>
        public static string SpinUpRpm {
            get {
                return ResourceManager.GetString("SpinUpRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target RPM applied during the spin-up boost phase..
        /// </summary>
        public static string SpinUpRpmDesc {
            get {
                return ResourceManager.GetString("SpinUpRpmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables gradual fan deceleration to prevent sudden noise shifts..
        /// </summary>
        public static string StepDownGlideDesc {
            get {
                return ResourceManager.GetString("StepDownGlideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Down Glide.
        /// </summary>
        public static string StepDownGliding {
            get {
                return ResourceManager.GetString("StepDownGliding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Down Glide Rate.
        /// </summary>
        public static string StepDownRate {
            get {
                return ResourceManager.GetString("StepDownRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum RPM drop per second while cooling down..
        /// </summary>
        public static string StepDownRateDesc {
            get {
                return ResourceManager.GetString("StepDownRateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Down Protection Delta.
        /// </summary>
        public static string StepDownSpamDelta {
            get {
                return ResourceManager.GetString("StepDownSpamDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum target RPM change required before updating WMI during deceleration..
        /// </summary>
        public static string StepDownSpamDeltaDesc {
            get {
                return ResourceManager.GetString("StepDownSpamDeltaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Fan Level.
        /// </summary>
        public static string SyncFanLevel {
            get {
                return ResourceManager.GetString("SyncFanLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizes all fans to the highest calculated speed target..
        /// </summary>
        public static string SyncFanLevelDesc {
            get {
                return ResourceManager.GetString("SyncFanLevelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Fan.
        /// </summary>
        public static string SystemFan {
            get {
                return ResourceManager.GetString("SystemFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Speed.
        /// </summary>
        public static string TargetSpeed {
            get {
                return ResourceManager.GetString("TargetSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Change Threshold.
        /// </summary>
        public static string TempDeltaThreshold {
            get {
                return ResourceManager.GetString("TempDeltaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum temperature change (°C) required to trigger a fan speed recalculation..
        /// </summary>
        public static string TempDeltaThresholdDesc {
            get {
                return ResourceManager.GetString("TempDeltaThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces safe minimum fan speed thresholds at high temperatures..
        /// </summary>
        public static string ThermalSafetyNetDesc {
            get {
                return ResourceManager.GetString("ThermalSafetyNetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuning.
        /// </summary>
        public static string Tuning {
            get {
                return ResourceManager.GetString("Tuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI &amp; Monitoring.
        /// </summary>
        public static string UiAndMonitoring {
            get {
                return ResourceManager.GetString("UiAndMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Save Debounce Delay.
        /// </summary>
        public static string UiDebounceDelay {
            get {
                return ResourceManager.GetString("UiDebounceDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay (ms) before committing configuration changes to disk after curve node adjustments..
        /// </summary>
        public static string UiDebounceDelayDesc {
            get {
                return ResourceManager.GetString("UiDebounceDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Update Interval.
        /// </summary>
        public static string UiUpdateInterval {
            get {
                return ResourceManager.GetString("UiUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh interval (ms) for the monitoring panel..
        /// </summary>
        public static string UiUpdateIntervalDesc {
            get {
                return ResourceManager.GetString("UiUpdateIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Cached Snapshot for Forced Refresh.
        /// </summary>
        public static string UseCachedSnapshot {
            get {
                return ResourceManager.GetString("UseCachedSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses the cached sensor snapshot instead of waiting for a new polling cycle during forced refresh..
        /// </summary>
        public static string UseCachedSnapshotDesc {
            get {
                return ResourceManager.GetString("UseCachedSnapshotDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Fan Curve (WMI).
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Max Each Cycle in Full Speed.
        /// </summary>
        public static string WriteEachCycle {
            get {
                return ResourceManager.GetString("WriteEachCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write max RPM every calculation cycle in full speed mode.
        /// </summary>
        public static string WriteEachCycleDesc {
            get {
                return ResourceManager.GetString("WriteEachCycleDesc", resourceCulture);
            }
        }
    }
}
