//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Plugin.CustomFanCurve.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Plugin.CustomFanCurve.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Acceleration Response (RPM/step) 的本地化字符串。
        /// </summary>
        public static string AccelResponse {
            get {
                return ResourceManager.GetString("AccelResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max RPM increase per step, default 25 的本地化字符串。
        /// </summary>
        public static string AccelResponseDesc {
            get {
                return ResourceManager.GetString("AccelResponseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max RPM increase per step 的本地化字符串。
        /// </summary>
        public static string AccelResponseHint {
            get {
                return ResourceManager.GetString("AccelResponseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a new control point at the end of the curve 的本地化字符串。
        /// </summary>
        public static string AddNodeTooltip {
            get {
                return ResourceManager.GetString("AddNodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply to All Power Modes 的本地化字符串。
        /// </summary>
        public static string ApplyToAllModes {
            get {
                return ResourceManager.GetString("ApplyToAllModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable custom fan control in all power modes on Legion devices 的本地化字符串。
        /// </summary>
        public static string ApplyToAllModesDesc {
            get {
                return ResourceManager.GetString("ApplyToAllModesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic 的本地化字符串。
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPM Calculation Interval (ms) 的本地化字符串。
        /// </summary>
        public static string CalcInterval {
            get {
                return ResourceManager.GetString("CalcInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum delay between two RPM calculations, default 500ms 的本地化字符串。
        /// </summary>
        public static string CalcIntervalDesc {
            get {
                return ResourceManager.GetString("CalcIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculation Scheduling 的本地化字符串。
        /// </summary>
        public static string CalcScheduling {
            get {
                return ResourceManager.GetString("CalcScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Cache When Leaving Custom Mode 的本地化字符串。
        /// </summary>
        public static string ClearCacheOnLeave {
            get {
                return ResourceManager.GetString("ClearCacheOnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear cached RPM/temperature state 的本地化字符串。
        /// </summary>
        public static string ClearCacheOnLeaveDesc {
            get {
                return ResourceManager.GetString("ClearCacheOnLeaveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Fan 的本地化字符串。
        /// </summary>
        public static string CpuFan {
            get {
                return ResourceManager.GetString("CpuFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Speed 的本地化字符串。
        /// </summary>
        public static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug Mode 的本地化字符串。
        /// </summary>
        public static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output detailed debug logs when enabled 的本地化字符串。
        /// </summary>
        public static string DebugModeDesc {
            get {
                return ResourceManager.GetString("DebugModeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deceleration Response (RPM/step) 的本地化字符串。
        /// </summary>
        public static string DecelResponse {
            get {
                return ResourceManager.GetString("DecelResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max RPM decrease per step, default 12 的本地化字符串。
        /// </summary>
        public static string DecelResponseDesc {
            get {
                return ResourceManager.GetString("DecelResponseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max RPM decrease per step 的本地化字符串。
        /// </summary>
        public static string DecelResponseHint {
            get {
                return ResourceManager.GetString("DecelResponseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete this node 的本地化字符串。
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Custom Fan Curve 的本地化字符串。
        /// </summary>
        public static string EnableCurve {
            get {
                return ResourceManager.GetString("EnableCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore BIOS auto fan control when disabled 的本地化字符串。
        /// </summary>
        public static string EnableCurveDesc {
            get {
                return ResourceManager.GetString("EnableCurveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Custom Fan Curve 的本地化字符串。
        /// </summary>
        public static string EnableCustomFanCurve {
            get {
                return ResourceManager.GetString("EnableCustomFanCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Spin-Up Boost 的本地化字符串。
        /// </summary>
        public static string EnableSpinUp {
            get {
                return ResourceManager.GetString("EnableSpinUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fan Speed 的本地化字符串。
        /// </summary>
        public static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Refresh on Enable 的本地化字符串。
        /// </summary>
        public static string ForceRefreshOnEnable {
            get {
                return ResourceManager.GetString("ForceRefreshOnEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Refresh on Mode Switch 的本地化字符串。
        /// </summary>
        public static string ForceRefreshOnSwitch {
            get {
                return ResourceManager.GetString("ForceRefreshOnSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re-apply fan control after switching power modes 的本地化字符串。
        /// </summary>
        public static string ForceRefreshOnSwitchDesc {
            get {
                return ResourceManager.GetString("ForceRefreshOnSwitchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Speed... 的本地化字符串。
        /// </summary>
        public static string FullSpeedActive {
            get {
                return ResourceManager.GetString("FullSpeedActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Settings 的本地化字符串。
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open global settings 的本地化字符串。
        /// </summary>
        public static string GlobalSettingsTooltip {
            get {
                return ResourceManager.GetString("GlobalSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Fan 的本地化字符串。
        /// </summary>
        public static string GpuFan {
            get {
                return ResourceManager.GetString("GpuFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Zero Temperature 的本地化字符串。
        /// </summary>
        public static string IgnoreZeroTemp {
            get {
                return ResourceManager.GetString("IgnoreZeroTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip processing when sensor returns 0 的本地化字符串。
        /// </summary>
        public static string IgnoreZeroTempDesc {
            get {
                return ResourceManager.GetString("IgnoreZeroTempDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live Monitor 的本地化字符串。
        /// </summary>
        public static string LiveMonitor {
            get {
                return ResourceManager.GetString("LiveMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Speed 的本地化字符串。
        /// </summary>
        public static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run all fans at maximum speed 的本地化字符串。
        /// </summary>
        public static string MaxSpeedTooltip {
            get {
                return ResourceManager.GetString("MaxSpeedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode Switch 的本地化字符串。
        /// </summary>
        public static string ModeSwitch {
            get {
                return ResourceManager.GetString("ModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power/Thermal Mode Switch Behavior 的本地化字符串。
        /// </summary>
        public static string ModeSwitchTitle {
            get {
                return ResourceManager.GetString("ModeSwitchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overheat full speed 的本地化字符串。
        /// </summary>
        public static string Over50MinRpm {
            get {
                return ResourceManager.GetString("Over50MinRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protection &amp; Response 的本地化字符串。
        /// </summary>
        public static string ProtectionAndResponse {
            get {
                return ResourceManager.GetString("ProtectionAndResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to restore custom curve 的本地化字符串。
        /// </summary>
        public static string RecoverCurve {
            get {
                return ResourceManager.GetString("RecoverCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Count 的本地化字符串。
        /// </summary>
        public static string RefreshCount {
            get {
                return ResourceManager.GetString("RefreshCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of refresh cycles after mode switch, default 2 的本地化字符串。
        /// </summary>
        public static string RefreshCountDesc {
            get {
                return ResourceManager.GetString("RefreshCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh Interval (ms) 的本地化字符串。
        /// </summary>
        public static string RefreshInterval {
            get {
                return ResourceManager.GetString("RefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay between multiple refreshes, default 250ms 的本地化字符串。
        /// </summary>
        public static string RefreshIntervalDesc {
            get {
                return ResourceManager.GetString("RefreshIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes take effect immediately after clicking Save. 的本地化字符串。
        /// </summary>
        public static string SaveHint {
            get {
                return ResourceManager.GetString("SaveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sensor &amp; Calc 的本地化字符串。
        /// </summary>
        public static string SensorAndCalc {
            get {
                return ResourceManager.GetString("SensorAndCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sensor Polling Interval (ms) 的本地化字符串。
        /// </summary>
        public static string SensorInterval {
            get {
                return ResourceManager.GetString("SensorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval for reading temperature data, default 500ms 的本地化字符串。
        /// </summary>
        public static string SensorIntervalDesc {
            get {
                return ResourceManager.GetString("SensorIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sensor Polling 的本地化字符串。
        /// </summary>
        public static string SensorPolling {
            get {
                return ResourceManager.GetString("SensorPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Settings 的本地化字符串。
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Settings — Custom Fan Curve (WMI) 的本地化字符串。
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spin-Up Boost 的本地化字符串。
        /// </summary>
        public static string SpinUpBoost {
            get {
                return ResourceManager.GetString("SpinUpBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When a fan is stopped, it needs a higher initial RPM to overcome static friction.
        ///With spin-up boost enabled, the system briefly runs the fan at a higher RPM before settling to the target. 的本地化字符串。
        /// </summary>
        public static string SpinUpDesc {
            get {
                return ResourceManager.GetString("SpinUpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spin-Up Duration (ms) 的本地化字符串。
        /// </summary>
        public static string SpinUpDuration {
            get {
                return ResourceManager.GetString("SpinUpDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How long the spin-up RPM lasts, default 300ms 的本地化字符串。
        /// </summary>
        public static string SpinUpDurationDesc {
            get {
                return ResourceManager.GetString("SpinUpDurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spin-Up RPM 的本地化字符串。
        /// </summary>
        public static string SpinUpRpm {
            get {
                return ResourceManager.GetString("SpinUpRpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temporary RPM during spin-up, default 3000 的本地化字符串。
        /// </summary>
        public static string SpinUpRpmDesc {
            get {
                return ResourceManager.GetString("SpinUpRpmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Fan 的本地化字符串。
        /// </summary>
        public static string SystemFan {
            get {
                return ResourceManager.GetString("SystemFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target fan speed percentage (0-100) 的本地化字符串。
        /// </summary>
        public static string TargetPercent {
            get {
                return ResourceManager.GetString("TargetPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Speed 的本地化字符串。
        /// </summary>
        public static string TargetSpeed {
            get {
                return ResourceManager.GetString("TargetSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temperature Change Threshold (°C) 的本地化字符串。
        /// </summary>
        public static string TempDeltaThreshold {
            get {
                return ResourceManager.GetString("TempDeltaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum temperature change to trigger recalculation, default 0.5°C 的本地化字符串。
        /// </summary>
        public static string TempDeltaThresholdDesc {
            get {
                return ResourceManager.GetString("TempDeltaThresholdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temperature 的本地化字符串。
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temperature value (°C) 的本地化字符串。
        /// </summary>
        public static string TemperatureUnit {
            get {
                return ResourceManager.GetString("TemperatureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI &amp; Monitoring 的本地化字符串。
        /// </summary>
        public static string UiAndMonitoring {
            get {
                return ResourceManager.GetString("UiAndMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Update Interval (ms) 的本地化字符串。
        /// </summary>
        public static string UiUpdateInterval {
            get {
                return ResourceManager.GetString("UiUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor panel refresh interval, default 1000ms 的本地化字符串。
        /// </summary>
        public static string UiUpdateIntervalDesc {
            get {
                return ResourceManager.GetString("UiUpdateIntervalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Cached Snapshot for Forced Refresh 的本地化字符串。
        /// </summary>
        public static string UseCachedSnapshot {
            get {
                return ResourceManager.GetString("UseCachedSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instead of waiting for new sensor readings 的本地化字符串。
        /// </summary>
        public static string UseCachedSnapshotDesc {
            get {
                return ResourceManager.GetString("UseCachedSnapshotDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Fan Curve (WMI) 的本地化字符串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write Max Each Cycle in Full Speed 的本地化字符串。
        /// </summary>
        public static string WriteEachCycle {
            get {
                return ResourceManager.GetString("WriteEachCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write max RPM every calculation cycle in full speed mode 的本地化字符串。
        /// </summary>
        public static string WriteEachCycleDesc {
            get {
                return ResourceManager.GetString("WriteEachCycleDesc", resourceCulture);
            }
        }
    }
}
